# Generated by Django 4.2.21 on 2025-06-08 23:16

from django.db import migrations, models
import django.utils.timezone
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivefile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivefile',
            name='zip_file',
            field=models.FileField(upload_to=uploader.models.overwrite_upload_path),
        ),
    ]
