# Generated by Django 4.2.27 on 2026-04-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Backup Settings', max_length=100)),
                ('bot_token', models.CharField(blank=True, default='', max_length=255)),
                ('chat_id', models.CharField(blank=True, default='', max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('backup_database', models.BooleanField(default=True)),
                ('backup_media', models.BooleanField(default=False)),
                ('interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
