# Generated by Django 4.2.27 on 2026-04-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambackupsettings',
            name='interval_minutes',
        ),
        migrations.AddField(
            model_name='telegrambackupsettings',
            name='interval_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
