# Generated by Django 4.2.21 on 2026-04-10 14:59

import secrets

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _backfill_user_api_keys(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    UserAPIKey = apps.get_model("dashboard", "UserAPIKey")
    for user in User.objects.all():
        if not UserAPIKey.objects.filter(user_id=user.pk).exists():
            UserAPIKey.objects.create(user=user, api_key=secrets.token_urlsafe(32))


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(db_index=True, default=dashboard.models._new_urlsafe_api_key, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key_row', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User API key',
                'verbose_name_plural': 'User API keys',
            },
        ),
        migrations.RunPython(_backfill_user_api_keys, _noop_reverse),
    ]
