# Generated by Django 4.2.27 on 2026-04-21 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_userapikey_hmac_lookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoredRSAPrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fernet_ciphertext', models.TextField(help_text='Fernet-encrypted PEM text')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stored_rsa_private_key_row', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User stored RSA private key',
                'verbose_name_plural': 'User stored RSA private keys',
            },
        ),
    ]
