# Generated by Django 4.2.21 on 2026-05-19 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_user_stored_rsa_private_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCloudflareDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('zone_id', models.CharField(max_length=64)),
                ('api_token_ciphertext', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, choices=[('ok', 'OK'), ('error', 'Error'), ('warning', 'Warning')], default='', max_length=16)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudflare_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['domain_name'],
            },
        ),
        migrations.CreateModel(
            name='CloudflareSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=16)),
                ('domains_ok', models.PositiveIntegerField(default=0)),
                ('domains_failed', models.PositiveIntegerField(default=0)),
                ('log_text', models.TextField(blank=True, default='')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloudflare_sync_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='usercloudflaredomain',
            constraint=models.UniqueConstraint(fields=('user', 'domain_name'), name='dashboard_usercloudflaredomain_user_domain_uniq'),
        ),
    ]
