#!/usr/bin/env bash
# Server install steps for antibot (Debian/Ubuntu).
# Run only via repo root install.sh after the repo exists at INSTALL_DIR.
# Do not run this file manually unless you know what you are doing.
#
set -eo pipefail

INSTALL_DIR="${ANTIBOT_INSTALL_DIR:-/opt/antibot}"
VENV_PATH="${INSTALL_DIR}/env"
SERVICE_NAME="antibot"
BIND_ADDR="0.0.0.0:8000"

if [ ! -f "${INSTALL_DIR}/manage.py" ]; then
  echo "ERROR: Django project not found at ${INSTALL_DIR} (missing manage.py)."
  exit 1
fi

# Django superuser (no default password):
# - ANTIBOT_SUPERUSER_PASSWORD from environment, or generated → /root/antibot_superuser_credentials.txt
SU_USER="${ANTIBOT_SUPERUSER_USERNAME:-admin}"
SU_EMAIL="${ANTIBOT_SUPERUSER_EMAIL:-admin@localhost}"

PG_DB_NAME="antibot"
PG_DB_USER="antibot"
PG_DB_HOST="127.0.0.1"
PG_DB_PORT="5432"

echo "[1/8] Installing packages (apt, Redis, PostgreSQL, then .env, migrate, Gunicorn, cron)..."
sudo apt update
sudo apt install -y python3 python3-venv python3-pip git curl openssl postgresql postgresql-contrib redis-server

echo "[2/8] Redis..."
sudo systemctl enable redis-server
sudo systemctl start redis-server

echo "[3/8] Creating/updating Python venv..."
python3 -m venv "${VENV_PATH}"
"${VENV_PATH}/bin/pip" install --upgrade pip
[ -f "${INSTALL_DIR}/requirements.txt" ] && \
  "${VENV_PATH}/bin/pip" install -r "${INSTALL_DIR}/requirements.txt"

echo "[4/8] PostgreSQL and .env file..."
sudo systemctl enable postgresql
sudo systemctl start postgresql

PG_PASSWORD="$(openssl rand -hex 32)"

if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${PG_DB_USER}'" | grep -q 1; then
  sudo -u postgres psql -v ON_ERROR_STOP=1 -c "CREATE USER ${PG_DB_USER} WITH PASSWORD '${PG_PASSWORD}';"
else
  sudo -u postgres psql -v ON_ERROR_STOP=1 -c "ALTER USER ${PG_DB_USER} WITH PASSWORD '${PG_PASSWORD}';"
fi

if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${PG_DB_NAME}'" | grep -q 1; then
  sudo -u postgres psql -v ON_ERROR_STOP=1 -c "CREATE DATABASE ${PG_DB_NAME} OWNER ${PG_DB_USER};"
fi

sudo -u postgres psql -v ON_ERROR_STOP=1 -c "GRANT ALL PRIVILEGES ON DATABASE ${PG_DB_NAME} TO ${PG_DB_USER};"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${PG_DB_NAME}" -c "GRANT ALL ON SCHEMA public TO ${PG_DB_USER};" || true
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${PG_DB_NAME}" -c "GRANT CREATE ON SCHEMA public TO ${PG_DB_USER};" || true
sudo -u postgres psql -d "${PG_DB_NAME}" -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${PG_DB_USER};" 2>/dev/null || true
sudo -u postgres psql -d "${PG_DB_NAME}" -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${PG_DB_USER};" 2>/dev/null || true

# ALLOWED_HOSTS auto-detect (see README)
if [ -n "${ANTIBOT_ALLOWED_HOSTS:-}" ]; then
  ALLOWED_HOSTS_VALUE="${ANTIBOT_ALLOWED_HOSTS}"
  echo "[env] ALLOWED_HOSTS from ANTIBOT_ALLOWED_HOSTS (override)."
else
  ALLOWED_HOSTS_VALUE="$(
    {
      echo "127.0.0.1"
      echo "localhost"
      _hn="$(hostname 2>/dev/null || true)"
      if [ -n "${_hn}" ] && [ "${_hn}" != "localhost" ]; then echo "${_hn}"; fi
      if command -v ip >/dev/null 2>&1; then
        ip -4 route get 8.8.8.8 2>/dev/null | awk '{ for (i = 1; i < NF; i++) if ($i == "src") { print $(i + 1); exit } }' || true
      fi
      _hi="$(hostname -I 2>/dev/null || true)"
      if [ -n "${_hi}" ]; then
        echo "${_hi}" | awk '{ print $1 }'
      fi
      if command -v curl >/dev/null 2>&1; then
        curl -fsS --max-time 3 --connect-timeout 2 "https://api.ipify.org" 2>/dev/null || true
      fi
      if [ -n "${ANTIBOT_EXTRA_ALLOWED_HOSTS:-}" ]; then
        echo "${ANTIBOT_EXTRA_ALLOWED_HOSTS}" | tr ',' '\n'
      fi
    } | sed '/^$/d' | awk 'NF && !seen[$0]++' | paste -sd ','
  )"
  echo "[env] ALLOWED_HOSTS auto-detected: ${ALLOWED_HOSTS_VALUE}"
fi
if [ -z "${ALLOWED_HOSTS_VALUE}" ]; then
  ALLOWED_HOSTS_VALUE="127.0.0.1,localhost"
  echo "[warn] ALLOWED_HOSTS empty after detection; using 127.0.0.1,localhost only."
fi

ENV_FILE="${INSTALL_DIR}/.env"
DJANGO_SECRET_VALUE="$(openssl rand -hex 48)"
umask 077
cat > "${ENV_FILE}" <<ENVEOF
# Generated by install (scripts/install-inner.sh). Edit ALLOWED_HOSTS or use ANTIBOT_* on next install.
DJANGO_ENV=production
DJANGO_SECRET_KEY=${DJANGO_SECRET_VALUE}
ALLOWED_HOSTS=${ALLOWED_HOSTS_VALUE}
REDIS_URL=redis://127.0.0.1:6379/1
DB_NAME=${PG_DB_NAME}
DB_USER=${PG_DB_USER}
DB_PASSWORD=${PG_PASSWORD}
DB_HOST=${PG_DB_HOST}
DB_PORT=${PG_DB_PORT}
ENVEOF
chmod 600 "${ENV_FILE}" || true
echo "[DB] Wrote ${ENV_FILE} (PostgreSQL database=${PG_DB_NAME} user=${PG_DB_USER})."

if [ -n "${ANTIBOT_SUPERUSER_PASSWORD:-}" ]; then
  SU_PASS="${ANTIBOT_SUPERUSER_PASSWORD}"
  echo "[auth] Using Django superuser password from environment (ANTIBOT_SUPERUSER_PASSWORD)."
else
  SU_PASS="$(openssl rand -base64 32 | tr -d '\n')"
  CREDS_FILE="/root/antibot_superuser_credentials.txt"
  umask 077
  {
    echo "# Generated by install — delete after storing credentials securely."
    echo "ANTIBOT_SUPERUSER_USERNAME=${SU_USER}"
    echo "ANTIBOT_SUPERUSER_PASSWORD=${SU_PASS}"
    echo "ANTIBOT_SUPERUSER_EMAIL=${SU_EMAIL}"
  } > "${CREDS_FILE}"
  chmod 600 "${CREDS_FILE}" || true
  echo "[auth] Generated Django superuser password; read with: sudo cat ${CREDS_FILE}"
fi

echo "[5/8] migrate + superuser..."
cd "${INSTALL_DIR}"
"${VENV_PATH}/bin/python" "${INSTALL_DIR}/manage.py" migrate
DJANGO_SUPERUSER_USERNAME="${SU_USER}" \
DJANGO_SUPERUSER_EMAIL="${SU_EMAIL}" \
DJANGO_SUPERUSER_PASSWORD="${SU_PASS}" \
"${VENV_PATH}/bin/python" "${INSTALL_DIR}/manage.py" createsuperuser --noinput || true

echo "[collectstatic] Collecting static files..."
"${VENV_PATH}/bin/python" "${INSTALL_DIR}/manage.py" collectstatic --noinput || \
  echo "[warn] collectstatic failed — check logs and STATIC_ROOT in settings."

echo "[6/8] Creating systemd unit (Gunicorn)..."
sudo tee /etc/systemd/system/${SERVICE_NAME}.service >/dev/null <<EOF
[Unit]
Description=${SERVICE_NAME} Django (Gunicorn)
After=network.target postgresql.service redis-server.service
Wants=postgresql.service redis-server.service

[Service]
User=$(whoami)
WorkingDirectory=${INSTALL_DIR}
Environment=PATH=${VENV_PATH}/bin
EnvironmentFile=-${INSTALL_DIR}/.env
ExecStart=${VENV_PATH}/bin/gunicorn --bind ${BIND_ADDR} --workers 2 --timeout 120 analytics_project.wsgi:application
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now ${SERVICE_NAME}

echo "[7/8] Configuring cron (Telegram backup)..."
CRON_CMD="*/10 * * * * cd ${INSTALL_DIR} && set -a && . ${INSTALL_DIR}/.env && set +a && ${VENV_PATH}/bin/python manage.py run_telegram_backup >> ${INSTALL_DIR}/backup.log 2>&1"

(crontab -l 2>/dev/null | grep -v "run_telegram_backup"; echo "$CRON_CMD") | crontab -

echo "Cron job added:"
crontab -l

echo "[8/8] Service status:"
systemctl status ${SERVICE_NAME} --no-pager || true

# Pick a sensible host for the login URL (first non-loopback from ALLOWED_HOSTS, else 127.0.0.1)
_LOGIN_PORT="${BIND_ADDR##*:}"
_LOGIN_HOST=""
IFS=',' read -ra _ah_arr <<< "${ALLOWED_HOSTS_VALUE}"
for h in "${_ah_arr[@]}"; do
  h="$(echo "${h}" | tr -d '[:space:]')"
  [ -z "${h}" ] && continue
  if [ "${h}" != "127.0.0.1" ] && [ "${h}" != "localhost" ]; then
    _LOGIN_HOST="${h}"
    break
  fi
done
[ -z "${_LOGIN_HOST}" ] && _LOGIN_HOST="127.0.0.1"
_LOGIN_URL="http://${_LOGIN_HOST}:${_LOGIN_PORT}/accounts/login/"
_DASH_URL="http://${_LOGIN_HOST}:${_LOGIN_PORT}/dashboard/"

echo ""
echo "══════════════════════════════════════════════════════════════"
echo "  Install complete"
echo "══════════════════════════════════════════════════════════════"
echo "  Username:     ${SU_USER}"
echo "  Password:     ${SU_PASS}"
echo "  Login URL:    ${_LOGIN_URL}"
echo "  Dashboard:    ${_DASH_URL}"
echo "  Local login:  http://127.0.0.1:${_LOGIN_PORT}/accounts/login/"
echo "══════════════════════════════════════════════════════════════"
echo "  Save the password; change it after first login if possible."
echo "  If the superuser already existed, createsuperuser was skipped — use the old password or:"
echo "    cd ${INSTALL_DIR} && source env/bin/activate && set -a && . .env && set +a && python manage.py changepassword ${SU_USER}"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "Deploy path: ${INSTALL_DIR} — use uninstall.sh to remove this install only."
