# Generated by Django 4.2.21 on 2025-06-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSafeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
