# Generated by Django 4.2.21 on 2025-06-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_googlesafecheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('keyword', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
