# Generated by Django 4.2.27 on 2026-04-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_telegrambackupsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramBackupSettings',
        ),
    ]
