# Generated by Django 4.2.21 on 2026-05-20 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0005_delete_telegrambackupsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCheckJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('numbers_text', models.TextField()),
                ('account_names', models.JSONField(blank=True, default=list)),
                ('speed', models.CharField(default='normal', max_length=16)),
                ('fetch_presence', models.BooleanField(default=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('run_dir', models.CharField(blank=True, max_length=512)),
                ('checked_count', models.PositiveIntegerField(default=0)),
                ('live_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('result_summary', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_check_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
