# Generated by Django 4.2.27 on 2026-05-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_whatsappcheckjob_local_trunk_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcheckjob',
            name='fetch_presence',
            field=models.BooleanField(default=False),
        ),
    ]
