# Generated by Django 4.2.21 on 2026-05-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0008_whatsappcheckjob_fetch_presence_default_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappcheckjob",
            name="previously_checked_numbers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="WhatsAppVerifiedNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                (
                    "last_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_numbers_recorded",
                        to="tools.whatsappcheckjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-first_seen"],
            },
        ),
    ]
