# Generated by Django 4.2.21 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0010_whatsappaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappcheckjob",
            name="previously_checked_numbers",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
