# Generated by Django 4.2.21 on 2025-05-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_blockedbrowser_blockedhostname_blockedip_blockedisp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='BlockRule',
        ),
    ]
