# Generated by Django 4.2.21 on 2025-05-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_allowedcountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
