# Generated by Django 4.2.21 on 2025-05-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_rejectedvisitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedcountry',
            options={'verbose_name_plural': '6 - Country'},
        ),
        migrations.AlterModelOptions(
            name='blockedbrowser',
            options={'verbose_name_plural': '4 - Browser'},
        ),
        migrations.AlterModelOptions(
            name='blockedhostname',
            options={'verbose_name_plural': '5 - Hostname'},
        ),
        migrations.AlterModelOptions(
            name='blockedip',
            options={'verbose_name_plural': '1 - IP'},
        ),
        migrations.AlterModelOptions(
            name='blockedisp',
            options={'verbose_name_plural': '2 - ISP'},
        ),
        migrations.AlterModelOptions(
            name='blockedos',
            options={'verbose_name_plural': '3 - OS'},
        ),
        migrations.AlterModelOptions(
            name='iplog',
            options={'verbose_name_plural': 'Bot IP'},
        ),
        migrations.AlterModelOptions(
            name='rejectedvisitor',
            options={'verbose_name_plural': 'Deny Logs'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name_plural': 'Logs'},
        ),
    ]
