# Generated by Django 4.2.21 on 2025-05-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_allowedcountry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedcountry',
            options={'verbose_name_plural': '3 - Allowed Countries'},
        ),
        migrations.AddField(
            model_name='allowedcountry',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
