# Generated by Django 4.2.21 on 2025-06-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_allowedcountry_options_allowedcountry_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedcountry',
            options={'verbose_name_plural': '7 - Allowed Country Codes'},
        ),
        migrations.RemoveField(
            model_name='allowedcountry',
            name='name',
        ),
        migrations.AlterField(
            model_name='allowedcountry',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
