# Generated by Django 4.2.21 on 2025-06-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_allowedcountry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iplog',
            options={},
        ),
        migrations.AddField(
            model_name='iplog',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
