# Generated by Django 4.2.21 on 2025-06-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_allowedcountry_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedcountry',
            name='name',
        ),
    ]
