# Generated by Django 4.2.21 on 2025-06-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_remove_allowedcountry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedcountry',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
