# Generated by Django 4.2.21 on 2025-06-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_allowedcountry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedcountry',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
