# Generated by Django 4.2.27 on 2025-12-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_alter_allowedcountry_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSubnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(max_length=43, unique=True)),
            ],
            options={
                'verbose_name_plural': '1.1 - Subnets',
            },
        ),
    ]
