# Generated by Django 4.2.27 on 2025-12-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_blockedsubnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedvisitor',
            name='b_subnet',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='visitor',
            name='b_subnet',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
