# Generated by Django 4.2.27 on 2025-12-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_rejectedvisitor_b_subnet_visitor_b_subnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('isp', models.CharField(blank=True, default='', max_length=255)),
                ('subnet', models.CharField(blank=True, default='', max_length=64)),
                ('as_type', models.CharField(blank=True, default='', max_length=64)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_hosting', models.BooleanField(default=False)),
                ('is_tor', models.BooleanField(default=False)),
                ('is_vpn', models.BooleanField(default=False)),
                ('is_satellite', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IP Info',
            },
        ),
    ]
