# Generated by Django 4.2.21 on 2026-04-10 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0017_ipinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipinfo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_info_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iplog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_hit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rejectedvisitor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_visitor_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ipinfo',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='iplog',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AddConstraint(
            model_name='ipinfo',
            constraint=models.UniqueConstraint(fields=('owner', 'ip_address'), name='tracker_ipinfo_owner_ip_uniq'),
        ),
        migrations.AddConstraint(
            model_name='iplog',
            constraint=models.UniqueConstraint(fields=('owner', 'ip_address'), name='tracker_iplog_owner_ip_uniq'),
        ),
    ]
